name 'formatron_ntp_server'
version '0.1.1'
description 'Formatron NTP server cookbook'
maintainer 'Peter Halliday'
maintainer_email 'pghalliday@gmail.com'
source_url 'https://github.com/formatron/ntp-server-cookbook'
issues_url 'https://github.com/formatron/ntp-server-cookbook/issues'
supports 'ubuntu'
depends 'formatron_common'
depends 'formatron_ntp'
